// 沒用到
export const User = {
    id: '',
    firstName: '',
    lastName: '',
    email: '',
    state: '',
};
 
export const fakeData = [
    // {
    //   id: '',
    //   strategy: '',
    //   month: '',
    //   starttime: '',
    //   endtime: '',
    //   power: '',
    // },
  ];
//   export const fakeData = [
//     {
//       id: '9s41rp',
//       strategy: 'Kelvin',
//       month: 'Langosh',
//       starttime: 'Jerod14@hotmail.com',
//       endtime: 'Ohio',
//       power: '1',
//     },
//     {
//       id: '08m6rx',
//       strategy: 'Molly',
//       month: 'Purdy',
//       starttime: 'Hugh.Dach79@hotmail.com',
//       endtime: 'Rhode Island',
//       power: '1',
//     },
//     {
//       id: '5ymtrc',
//       strategy: 'Henry',
//       month: 'Lynch',
//       starttime: 'Camden.Macejkovic@yahoo.com',
//       endtime: 'California',
//       power: '1',
//     },
//     {
//       id: 'ek5b97',
//       strategy: 'Glenda',
//       month: 'Douglas',
//       starttime: 'Eric0@yahoo.com',
//       endtime: 'Montana',
//       power: '1',
//     },
//     {
//       id: 'xxtydd',
//       strategy: 'Leone',
//       month: 'Williamson',
//       starttime: 'Ericka_Mueller52@yahoo.com',
//       endtime: 'Colorado',
//       power: '1',
//     },
//     {
//       id: 'wzxj9m',
//       strategy: 'Mckenna',
//       month: 'Friesen',
//       starttime: 'Veda_Feeney@yahoo.com',
//       endtime: 'New York',
//       power: '1',
//     },
//     {
//       id: '21dwtz',
//       strategy: 'Wyman',
//       month: 'Jast',
//       starttime: 'Melvin.Pacocha@yahoo.com',
//       endtime: 'Montana',
//       power: '1',
//     },
//     {
//       id: 'o8oe4k',
//       strategy: 'Janick',
//       month: 'Willms',
//       starttime: 'Delfina12@gmail.com',
//       endtime: 'Nebraska',
//       power: '1',
//     },
//   ];
 
  export const usStates = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
  ];
